#!/bin/sh

FILE1=/tmp/calc1-$$
FILE2=/tmp/calc2-$$
ERROR=/tmp/calc-err-$$

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

end () {
	rm -f $FILE1 $FILE2 $ERROR
	exit
}

while true
do
	$DIALOG --inputbox "Чего посчитать?" 8 35 2> $FILE1 || end
	if cat $FILE1 | nc localhost 1234 > $FILE2 2>$ERROR
	then
		MSG="Итого: `cat $FILE2`\n\nПродолжаем?"
		$DIALOG --yesno "$MSG" 7 20 || end
	else
		MSG="Ошибочка вышла:\n\n`cat $ERROR`\n\nПродолжаем?"
		$DIALOG --yesno "$MSG" 10 35 || end
	fi
done
